export const COPY = {
  'pt-BR': {
    title: 'Regressão linear vs classificador logístico radial',
    subtitle: 'Mesmo dataset, duas hipóteses e duas fronteiras de decisão.',
    controls: {
      generate: 'Gerar novo conjunto',
      start: 'Iniciar treino',
      pause: 'Pausar',
      reset: 'Resetar modelos',
      speed: 'Velocidade',
    },
    panels: {
      linear: {
        title: 'Regressão linear',
        subtitle: 'Modelo linear puro • sem sigmoide',
      },
      sigmoid: {
        title: 'Classificador logístico radial',
        subtitle: 'Feature radial + saída sigmoide',
      },
    },
    tabs: {
      graph: 'Grafo iterativo',
      code: 'Código completo',
    },
    graph: {
      metrics: 'Métricas',
      math: 'Notação matemática',
      interpretation: 'Interpretação',
      console: 'Mini console',
    },
    linear: {
      badge: 'Sem sigmoide',
      epoch: 'Época',
      loss: 'MSE',
      acc: 'Acurácia (limiar 0,5)',
      equation: 'Equação atual',
      activation: 'Saída contínua',
      mathLines: [
        'prediction = w1x1 + w2x2 + b',
        'error = prediction - label',
        'loss = (1/n) Σ error^2',
        'step() ajusta w1, w2 e b pela média do erro',
      ],
      defs: [
        'x1, x2 = coordenadas da amostra',
        'label = rótulo real (0 ou 1)',
        'prediction = saída da combinação linear',
        'loss = erro quadrático médio',
        'acc = proporção de acertos com limiar 0,5',
      ],
      bullets: [
        'A saída é uma combinação linear das coordenadas.',
        'A loss mede o erro quadrático médio entre saída e rótulo.',
        'Não há sigmoide: o score continua linear.',
        'A fronteira é uma reta, então círculos concêntricos seguem difíceis.',
      ],
    },
    sigmoid: {
      badge: 'Com sigmoide',
      epoch: 'Época',
      loss: 'Loss',
      acc: 'Acurácia',
      equation: 'Equação atual',
      activation: 'σ(z) = 1 / (1 + e^-z)',
      mathLines: [
        'r² = x² + y²',
        'ŷ = σ(w · r² + b)',
        'L = -(1/n) Σ [y log(ŷ) + (1 - y) log(1 - ŷ)]',
        'step() ajusta w e b pela média do erro',
      ],
      defs: [
        'x, y = coordenadas da amostra',
        'r² = feature radial (distância ao quadrado)',
        'w = peso aplicado ao raio ao quadrado',
        'b = viés do classificador',
        'ŷ = probabilidade prevista',
      ],
      bullets: [
        'A feature radial transforma o problema em algo separável por círculo.',
        'A sigmoide converte o score em probabilidade.',
        'A loss é entropia cruzada binária.',
        'A fronteira de decisão vira um anel/círculo, não uma reta.',
      ],
    },
    console: {
      idle: 'aguardando treino',
      running: 'treinando',
      paused: 'pausado',
      completed: 'concluído',
      codeHint: 'troque para a aba de código para inspecionar a implementação',
      graphHint: 'use os controles acima para mudar dados, treino e velocidade',
    },
  },
  en: {
    title: 'Linear regression vs radial logistic classifier',
    subtitle: 'Same dataset, two hypotheses and two decision boundaries.',
    controls: {
      generate: 'Generate new dataset',
      start: 'Start training',
      pause: 'Pause',
      reset: 'Reset models',
      speed: 'Speed',
    },
    panels: {
      linear: {
        title: 'Linear regression',
        subtitle: 'Pure linear model • no sigmoid',
      },
      sigmoid: {
        title: 'Radial logistic classifier',
        subtitle: 'Radial feature + sigmoid output',
      },
    },
    tabs: {
      graph: 'Interactive graph',
      code: 'Full code',
    },
    graph: {
      metrics: 'Metrics',
      math: 'Math notation',
      interpretation: 'Interpretation',
      console: 'Mini console',
    },
    linear: {
      badge: 'No sigmoid',
      epoch: 'Epoch',
      loss: 'MSE',
      acc: 'Accuracy (0.5 threshold)',
      equation: 'Current equation',
      activation: 'Continuous output',
      mathLines: [
        'prediction = w1x1 + w2x2 + b',
        'error = prediction - label',
        'loss = (1/n) Σ error^2',
        'step() updates w1, w2 and b from the mean error',
      ],
      defs: [
        'x1, x2 = sample coordinates',
        'label = ground-truth label (0 or 1)',
        'prediction = linear combination output',
        'loss = mean squared error',
        'acc = fraction correct with a 0.5 threshold',
      ],
      bullets: [
        'The output is a linear combination of the coordinates.',
        'Loss measures the mean squared error between output and label.',
        'There is no sigmoid: the score stays linear.',
        'The boundary is a line, so concentric circles stay hard.',
      ],
    },
    sigmoid: {
      badge: 'With sigmoid',
      epoch: 'Epoch',
      loss: 'Loss',
      acc: 'Accuracy',
      equation: 'Current equation',
      activation: 'σ(z) = 1 / (1 + e^-z)',
      mathLines: [
        'r² = x² + y²',
        'ŷ = σ(w · r² + b)',
        'L = -(1/n) Σ [y log(ŷ) + (1 - y) log(1 - ŷ)]',
        'step() updates w and b from the mean error',
      ],
      defs: [
        'x, y = coordinates of the sample',
        'r² = radial feature (squared distance)',
        'w = weight applied to squared radius',
        'b = classifier bias',
        'ŷ = predicted probability',
      ],
      bullets: [
        'The radial feature turns the problem into something circle-separable.',
        'The sigmoid converts the score into a probability.',
        'Loss is binary cross-entropy.',
        'The decision boundary becomes a ring/circle, not a line.',
      ],
    },
    console: {
      idle: 'waiting for training',
      running: 'training',
      paused: 'paused',
      completed: 'completed',
      codeHint: 'switch to the code tab to inspect the implementation',
      graphHint: 'use the controls above to change data, training and speed',
    },
  },
} as const;
